# NumPy 실습 문제

아래 문제에 대해 풀이하시오.
(numpy 모듈 import 필요)


다음 리스트 `[1, 2, 3, 4, 5]`를 ndarray로 변환하고, 배열의 차원(ndim)과 형태(shape)을 출력하시오.

In [2]:
import numpy as np
# numpy 모듈 import / np 별칭 부여
print('나')
arr = np.array([1, 2, 3, 4, 5])
print(f'ndim : {arr.ndim} / shape : {arr.shape}')

print('강사님')
data = [1, 2 , 3 , 4, 5]
arr = np.array([data])
print(arr)
print(type(arr))

# ndim  : 배열의 차원수
# shape : 배열의 형태
print(f'배열의 차원 수 : {arr.ndim}')
print(f'배열의 형태    : {arr.shape}') 

나
ndim : 1 / shape : (5,)
강사님
[[1 2 3 4 5]]
<class 'numpy.ndarray'>
배열의 차원 수 : 2
배열의 형태    : (1, 5)



`np.arange()`를 이용해 0부터 20까지의 짝수로 이루어진 배열을 생성하시오.

In [8]:
print('나')
arr = np.arange(0,21,2)
print(arr)

print('강사님')
#np.arange(시작값, 끝값, 간격) : 순차적으로 배열의 요소(데이터)를 생성해주는 함수
# - 시작값부터 끝값 -1 까지 간격의 크기만큼 숫자 나열

# 0 ~ 20 => 시작값 : 0, 끝값 : 21, 간격 : 2
# 0 _ 2 _ 4 ...

arr = np.arange(0, 21, 2)
print(arr)

나
[ 0  2  4  6  8 10 12 14 16 18 20]
강사님
[ 0  2  4  6  8 10 12 14 16 18 20]


다음 배열을 주어진 형태로 변환하시오.

In [ ]:
arr = np.arange(12)
# => np.arange(끝값) : 0 ~ 끝값 -1 까지 1 간격으로 숫자 생성. (1차원배열)

print('나')
# (3, 4)
result1 = arr.reshape(3, 4)
print(result1)
# (2, 3, 2)
print(arr.reshape(2, 3, 2))

print('\n강사님')
# 배열.reshape(형태)

# (3, 4)
# => 2차원 배열(x,y) : x행 y열 로 이루어짐
arr_2d = arr.reshape(3 , 4)
print(f'(3, 4) 형태로 변환 :\n {arr_2d}')

# (2, 3, 2)
# => 3차원 배열(p, x, y) : p면, x행, y열 로 이루어짐
arr_3d = arr.reshape(2, 3, 2)
print(f'\n(2, 3, 2) 형태로 변환 :\n {arr_3d}')

나
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

강사님
(3, 4) 형태로 변환 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

(2, 3, 2) 형태로 변환 :
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]



다음 제시된 배열에서, **3 이상인 값만 추출**하는 불리언 인덱싱 코드를 작성하시오.

In [ ]:
arr = np.array([1, 3, 5, 2, 8, 3])

print('나')
result = arr >= 3
print(arr[result])

print('\n강사님')
# 불리언 인덱싱 : 조건식의 결과 (True, False)를 가지고 인덱싱 처리. 벡터화 연산 적용
c_result = arr >= 3
print(c_result)

b_arr = arr[c_result]
print(b_arr)

print(arr[arr >= 3])
# 한줄에 입력해서 출력하기

나
[3 5 8 3]

강사님
[False  True  True False  True  True]
[3 5 8 3]
[3 5 8 3]



다음 제시된 2차원 배열에서 **두 번째 행**만 슬라이싱하여 출력하시오.

In [26]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print('나')
print(arr[1])

print('\n강사님')
# 슬라이싱 : 인덱스 범위를 지정하여 추출하는 방법
#       대상 [시작인덱스 : 끝인덱스 : 간격]
#       - 시작인덱스 (포함)   : 기본값 0
#       - 끝 인덱스 (미포함)  : 기본값 마지막인덱스 + 1
#       -     간격            : 기본값 1
print('* == 슬라이싱 == *')
print(arr[1:2:1])
print(arr[1:2])
print('* == 인덱싱 == *')
print(arr[1])

나
[40 50 60]

강사님
* == 슬라이싱 == *
[[40 50 60]]
[[40 50 60]]
* == 인덱싱 == *
[40 50 60]


아래 리스트 기반 반복문을 벡터화 연산으로 개선하시오.

In [27]:
data = [1, 2, 3, 4, 5]
print('나')
# 리스트 기반 처리
result = []
for x in data:
    result.append(x * 3 + 1)

# 벡터화 연산 처리
arr = np.array([1, 2, 3, 4 , 5])
result = arr * 3 + 1
print(result)

print('강사님')
data = [1, 2, 3, 4, 5]        # 파이썬의 리스트 타입
# 리스트 기반 처리
result = []
for x in data:
    result.append(x * 3 + 1)

# 벡터화 연산 처리
# => 넘파이에서 저굥ㅇ 가능한 기술 -> 넘파이 객체
# * 리스트 -> ndarray(넘파이 배열 객체) 변환
arr = np.array(data)

# 벡터화 연산 적용
vec_result = arr * 3 + 1
print(vec_result)


나
[ 4  7 10 13 16]
강사님
[ 4  7 10 13 16]



다음 제시된 배열에서 **모든 홀수에 10을 더하는 벡터화 연산**을 수행하시오.

In [32]:
print('나')
arr = np.array([1, 2, 3, 4, 5])
result = arr % 2 != 0
print(arr[result] + 10)

print('강사님')
arr = np.array([1, 2, 3, 4, 5])

# 모든 요소에 10을 더하기
print(arr + 10)

# 홀수에 해당하는 값 => 조건 : x % 2 != 0 / x % 2 == 1
print(arr[arr % 2 != 0])

# 홀수 데이터만 추출 후 10 더하기
arr_odd = (arr[arr % 2 != 0]) + 10
print(arr_odd)

odd_idx = np.where(arr % 2 != 0)
arr_odd = arr[odd_idx]

print(arr_odd + 10)

# ---------------------------------------------------------

# 모든 데이터에서 홀수에만 +10 하기
arr_odd = np.where(arr % 2 != 0, arr + 10, arr)
print(arr_odd)

나
[11 13 15]
강사님
[11 12 13 14 15]
[1 3 5]
[11 13 15]
[11 13 15]
[11  2 13  4 15]



다음 제시된 2차원 배열에서 **50보다 큰 값들만 추출하여** 새로운 배열로 만드시오.

In [35]:
arr = np.array([[12, 55, 72], [3, 88, 41], [60, 10, 99]])

print('나')
flatten_arr = arr.flatten()
result = flatten_arr > 50
print(flatten_arr[result])

print('강사님')
arr_1d = np.array([3, 88, 41])
print(arr_1d[ arr_1d> 50])
print(arr_1d[np.where(arr_1d > 50)])

c_result = arr > 50
print(c_result)

print(arr[c_result])

c_result = np.where(arr > 50)
print(c_result)
print(arr[c_result])

나
[55 72 88 60 99]
강사님
[88]
[88]
[[False  True  True]
 [False  True False]
 [ True False  True]]
[55 72 88 60 99]
(array([0, 0, 1, 2, 2]), array([1, 2, 1, 0, 2]))
[55 72 88 60 99]



브로드캐스팅을 이용하여 아래 배열에 값 5를 더하시오.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('나')
x = [5]
print(arr + x)
print(arr + 5)

print('강사님')
arr = np.array([[1, 2, 3], [4, 5, 6]])

scalar = 5             # 5 -> [5, 5, 5] -> [[5, 5, 5], [5, 5, 5]]
arr_0d = np.array(5)

print(type(scalar), type(arr_0d))
print(arr + scalar)
print(arr + arr_0d)


나
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  7  8]
 [ 9 10 11]]
강사님
<class 'int'> <class 'numpy.ndarray'>
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  7  8]
 [ 9 10 11]]



3차원 배열을 생성하여 shape, ndim, size를 출력하는 코드를 작성하시오.

In [38]:
print('나')
arr = np.arange(0,12).reshape(3,1,-1)
print(f'3D :\n {arr}')
print(f'shape : {arr.shape}')
print(f'ndim : {arr.ndim}')
print(f'size : {arr.size}')

print('강사님')
# 3차원 배열 생성 (p, x, y)
arr_3d = np.arange(27). reshape(3, 3, 3)  # 0 ~ 26
# arr_3d = np.zeros(shape=(3, 3, 3))        # 0. (27)
# arr_3d = np.ones(shape=(3, 3, 3))         # 1. (27)

print(arr_3d)

print(f'배열의 형태 (shape) : {arr_3d.shape}')
print(f'배열의 차원수 (ndim) : {arr_3d.ndim}')
print(f'요소 총 개수 (size) : {arr_3d.size}')

print(f'요소의 타입 (dtype) : {arr_3d.dtype}')

나
3D :
 [[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
shape : (3, 1, 4)
ndim : 3
size : 12
강사님
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
배열의 형태 (shape) : (3, 3, 3)
배열의 차원수 (ndim) : 3
요소 총 개수 (size) : 27
요소의 타입 (dtype) : int64


다음 배열에서 값을 최소 10, 최대 20으로 제한하시오.

In [39]:
print('나')
arr = np.array([3, 12, 25, 18, 7, 22])
result = np.clip(arr, 10, 20)
print(f'   원본     : {arr}')
print(f'클리핑 제한 : {result}')

print('강사님')
arr = np.array([3, 12, 25, 18, 7, 22])

# 값의 범위 제한 -> 클리핑
#     np.clip(배열, 최소값, 최대값) : 최소값, 최대값 포함 !

clip_arr = np.clip(arr, 10, 20)
print(clip_arr)


나
   원본     : [ 3 12 25 18  7 22]
클리핑 제한 : [10 12 20 18 10 20]
강사님
[10 12 20 18 10 20]


아래 데이터를 이용하여 학생별 총점을 구하시오.
단, reshape 및 브로드캐스팅을 활용할 것.

In [4]:
# 3명의 학생 시험 점수 데이터 (응시 시험 수 : 4)
scores = np.array([
    80, 70, 90, 60,
    88, 75, 66, 95,
    55, 65, 70, 60
])

# scores를 (3,4) 형태로 재배열
print('나')
result = scores.reshape(3, 4)
print(f'3x4 : \n{result}')

print('\n강사님')
scores_2d = scores.reshape(3, 4)
print(scores_2d)

# 각 시험의 가중치 정보를 참고하여 총점 계산
weights = np.array([0.2, 0.3, 0.3, 0.2])

# 총점= 시험A*r시험A의가중치​ + 시험B*r시험B의가중치 + 시험C*r시험C의가중치 + 시험D*r시험D의가중치
print('\n나')
r = result.sum(axis=0)
print(r)
result = r * weights
print(result)
# print(f'학생1 : {result[0]}')
# print(f'학생2 : {result[1]}')
# print(f'학생3 : {result[2]}')

print('\n강사님')
# [x, x, x, x] -> [[x, x, x, x], [x, x, x, x], [x, x, x, x]]
totals = scores_2d * weights
print(f'totals :\n {totals}')

# 합계 : sum
print(f'totals 합계 : {totals.sum(axis=1)}')

나
3x4 : 
[[80 70 90 60]
 [88 75 66 95]
 [55 65 70 60]]

강사님
[[80 70 90 60]
 [88 75 66 95]
 [55 65 70 60]]

나
[223 210 226 215]
[44.6 63.  67.8 43. ]

강사님
totals :
 [[16.  21.  27.  12. ]
 [17.6 22.5 19.8 19. ]
 [11.  19.5 21.  12. ]]
totals 합계 : [76.  78.9 63.5]
